---
title: "CleaningAndAnalysis"
author: "David Josephs"
date: "October 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r package loading, include=FALSE}
require(dplyr)
require(ggthemes)
```
# Cleaning and Analysis of the Beer and Brewery Data

```{r Data Import}
rawBeer <- read.csv(file = "raw/Beers.csv",header=TRUE, sep=",",stringsAsFactors=FALSE)
rawBrew <- read.csv(file= "raw/Breweries.csv", header=TRUE, sep=",", stringsAsFactors=FALSE)
```

Next we rename  the brewery IDs, and merge the data:

```{r merging}
Beer1 <- rawBeer %>% rename(Brewery_ID=Brewery_id)
Brew1 <- rawBrew %>% rename(Brewery_ID=Brew_ID)
Beer1 <- Beer1 %>% select(Name,Beer_ID,ABV,IBU,Style,Ounces,Brewery_ID)
BeerBrew <- merge(Beer1,Brew1, by='Brewery_ID')
```

Next we reorder the columns and give ourselves human readable names

```{r human readability}
BeerBrew <- BeerBrew %>% rename(BeerName = Name.x) %>% rename(BreweryName = Name.y)
BeerBrew <- BeerBrew %>% select(BeerName,Beer_ID,ABV,IBU,Style,Ounces,BreweryName,Brewery_ID,City,State)
```

Now we are on to the questions. Firt lets produce a count of NAs

```{r NA count}
na_count <- data.frame(sapply(BeerBrew, function(y) sum(length(which(is.na(y))))))
na_count<- na_count%>%rename(na_count=sapply.BeerBrew..function.y..sum.length.which.is.na.y.....)
```

Now lets get some state summary statistics

```{r state summaries}
StateSummary <- as.data.frame(BeerBrew %>% group_by(State) %>% summarise(medianABV = median(ABV, na.rm=TRUE),medianIBU = median(IBU, na.rm=TRUE),NumBreweries = n_distinct(Brewery_ID)))

```

Finally, lets find the max ABVs and IBUs

```{r maximums}
MaxABV <- BeerBrew %>% select(State, BeerName, ABV) %>% filter(!is.na(ABV)) %>% arrange(desc(ABV)) %>% slice(1)
MaxIBU <- BeerBrew %>% select(State, BeerName, IBU) %>% filter(!is.na(IBU)) %>% arrange(desc(IBU)) %>% slice(1)
```

And then lets see our output!

```{r output}
head(BeerBrew)
tail(BeerBrew)
StateSummary
na_count
MaxABV
MaxIBU
```


